#!/usr/bin/env python3
"""Map the active Omarchy palette onto Television's public theme tokens."""
import argparse
import fcntl
import json
import os
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path


def luminance(color):
    rgb = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4 for v in rgb]
    return sum(v * w for v, w in zip(linear, (0.2126, 0.7152, 0.0722)))


def contrast(a, b):
    light, dark = sorted((luminance(a), luminance(b)), reverse=True)
    return (light + 0.05) / (dark + 0.05)


def readable(color, foreground, grounds):
    """Retain the palette hue while lifting supporting text to readable contrast."""
    start = [int(color[i:i + 2], 16) for i in (1, 3, 5)]
    end = [int(foreground[i:i + 2], 16) for i in (1, 3, 5)]
    for step in range(101):
        candidate = '#' + ''.join(f'{round(a + (b - a) * step / 100):02x}' for a, b in zip(start, end))
        if min(contrast(candidate, ground) for ground in grounds) >= 4.5:
            return candidate
    return foreground


def render(colors):
    color_keys = {
        'background', 'foreground', 'dark_background', 'darker_background',
        'lighter_background', 'dark_foreground', 'accent', 'selection', 'muted',
        'red', 'orange', 'yellow', 'green', 'cyan', 'blue', 'magenta', 'bright_magenta',
    }
    for key in color_keys & colors.keys():
        value = colors[key]
        if not isinstance(value, str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', value):
            raise ValueError(f'Invalid hex color for {key}')
    bg, fg = colors['background'].lower(), colors['foreground'].lower()
    mode = colors.get('mode', 'dark' if luminance(bg) < luminance(fg) else 'light')
    if mode not in ('light', 'dark'):
        raise ValueError('Omarchy mode must be light or dark')

    def get(key, fallback):
        return colors.get(key, fallback).lower()

    surface = get('dark_background', bg)
    accent = get('accent', get('blue', fg))
    muted = readable(get('dark_foreground', fg), fg, (bg, surface))
    primary_text = max((bg, fg, '#000000', '#ffffff'), key=lambda c: contrast(c, accent))
    tokens = {
        'color-surface': bg, 'color-surface-muted': surface,
        'color-text': fg, 'color-text-muted': muted,
        'accent': accent, 'neutral': get('muted', muted),
        'red': get('red', accent), 'orange': get('orange', get('yellow', accent)),
        'yellow': get('yellow', accent), 'green': get('green', accent),
        'cyan': get('cyan', accent), 'blue': get('blue', accent),
        'purple': get('magenta', accent), 'pink': get('bright_magenta', get('magenta', accent)),
        'color-border': get('muted', muted),
        'color-primary-text': primary_text,
        'color-link': readable(accent, fg, (bg, surface)),
        'control-background': get('lighter_background', surface),
    }
    css = '/* Generated by sync.py from the active Omarchy colors.toml. */\n:root {\n'
    css += ''.join(f'  --{key}: {value};\n' for key, value in tokens.items())
    css += '}\n\n/* Application-only paint; shared semantic tokens above also reach artifacts. */\n'
    css += ':root[data-television-document="app"] {\n'
    css += f'  --app-wallpaper-image: none;\n  --app-wallpaper: {get("darker_background", surface)};\n'
    css += '  --wallpaper-overlay-background: var(--color-surface-muted);\n'
    css += f'  --channel-background-selected: {get("selection", surface)};\n'
    css += '  --channel-text-color-selected: var(--color-text);\n'
    css += '  --frame-titlebar-border-color: var(--color-border);\n}\n'
    return css, mode


def write_changed(path, content):
    if path.exists() and path.read_text() == content:
        return False
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name + '-', dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as out:
            out.write(content)
            os.fchmod(out.fileno(), 0o644)
        os.replace(temporary, path)
        return True
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--colors', type=Path, help='Palette override for offline verification')
    parser.add_argument('--no-activate', action='store_true', help='Generate without contacting Television')
    parser.add_argument('--require-activation', action='store_true', help='Exit unsuccessfully when activation must be retried')
    parser.add_argument('--force-activate', action='store_true', help='Refresh registry even if palette and selection are unchanged')
    args = parser.parse_args()
    package = Path(__file__).resolve().parent
    current = Path.home() / '.local/state/omarchy/current'
    palette = args.colors or current / 'theme/colors.toml'
    if not palette.exists() and args.colors is None:
        palette = Path(os.environ.get('XDG_CONFIG_HOME', Path.home() / '.config')) / 'omarchy/current/theme/colors.toml'
    with (package / '.sync.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        colors = tomllib.loads(palette.read_text())
        css, mode = render(colors)
        manifest = json.loads((package / 'manifest.json').read_text())
        manifest['colorScheme'] = mode
        name_path = current / 'theme.name'
        theme_name = name_path.read_text().strip() if args.colors is None and name_path.exists() else palette.parent.name
        state_path = package / 'sync-state.json'
        try:
            previous = json.loads(state_path.read_text())
        except (OSError, ValueError):
            previous = {}
        if not isinstance(previous, dict):
            previous = {}
        changed = any([
            write_changed(package / 'theme.css', css),
            write_changed(package / 'manifest.json', json.dumps(manifest, indent=2) + '\n'),
        ])
        state = {'omarchyTheme': theme_name, 'palette': str(palette), 'colorScheme': mode,
                 'activationPending': changed or args.force_activate or previous.get('activationPending', True)}
        write_changed(package / 'sync-state.json', json.dumps(state, indent=2) + '\n')
        print(f'Omarchy Television theme synced: {theme_name} ({mode})')
        if not args.no_activate:
            try:
                if not state['activationPending']:
                    selection = subprocess.run(['tv', 'focus-status'], capture_output=True, text=True, timeout=15)
                    if selection.returncode == 0 and json.loads(selection.stdout).get('activeThemeName') == package.name:
                        print('Palette and active theme are already current.')
                        return 0
                state['activationPending'] = True
                write_changed(state_path, json.dumps(state, indent=2) + '\n')
                result = subprocess.run(['tv', 'set-theme', package.name], capture_output=True, text=True, timeout=15)
                if result.returncode:
                    print('Television activation failed; the saved palette remains pending for retry.', file=sys.stderr)
                    print(result.stderr.strip() or result.stdout.strip(), file=sys.stderr)
                    return 1 if args.require_activation else 0
                else:
                    state['activationPending'] = False
                    write_changed(state_path, json.dumps(state, indent=2) + '\n')
                    print(result.stdout.strip())
            except (OSError, ValueError, subprocess.TimeoutExpired) as error:
                print(f'Television activation deferred: {error}', file=sys.stderr)
                state['activationPending'] = True
                write_changed(state_path, json.dumps(state, indent=2) + '\n')
                return 1 if args.require_activation else 0
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError) as error:
        print(f'Omarchy Television sync failed: {error}', file=sys.stderr)
        sys.exit(1)
